# Generated by Django 5.2.3 on 2025-06-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Capability Title')),
                ('description', models.TextField(help_text='Brief description of the capability', verbose_name='Description')),
                ('image', models.ImageField(upload_to='capabilities/', verbose_name='Image')),
                ('image_alt_text', models.CharField(max_length=255, verbose_name='Image Alt Text')),
                ('order', models.IntegerField(default=0, help_text='Display order of capabilities', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Feature Title')),
                ('description', models.TextField(help_text='Brief description of the feature', verbose_name='Description')),
                ('icon_class', models.CharField(help_text='Font Awesome icon class, e.g., fa fa-cogs', max_length=100, verbose_name='Icon Class')),
                ('order', models.IntegerField(default=0, help_text='Display order of features', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('short_description', models.TextField(help_text='Brief tagline or category for the product, used on the homepage', verbose_name='Short Description')),
                ('hero_image', models.ImageField(help_text='Primary image for homepage slider and product detail carousel', upload_to='product_heroes/', verbose_name='Hero Image')),
                ('hero_image_alt_text', models.CharField(max_length=255, verbose_name='Hero Image Alt Text')),
                ('main_description', models.TextField(help_text='Introductory paragraph on the product detail page', verbose_name='Main Description')),
                ('conclusion_text', models.TextField(blank=True, help_text='Concluding paragraph on the product detail page', null=True, verbose_name='Conclusion Text')),
                ('url_slug', models.SlugField(help_text='URL-friendly identifier for the product', unique=True, verbose_name='URL Slug')),
                ('order', models.IntegerField(default=0, help_text='Display order of products on the homepage slider', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Service Name')),
                ('short_description', models.TextField(help_text='Brief description of the service', verbose_name='Short Description')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='Service Image')),
                ('image_alt_text', models.CharField(max_length=255, verbose_name='Service Image Alt Text')),
                ('url_slug', models.SlugField(help_text='URL-friendly identifier for the service', unique=True, verbose_name='URL Slug')),
                ('order', models.IntegerField(default=0, help_text='Display order of service cards', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('description', models.TextField(help_text='Brief description of the event', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text='Display order of timeline events', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['year', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('page_name', models.CharField(help_text='e.g., home, about, service', max_length=50, verbose_name='Page Name')),
                ('section_identifier', models.CharField(help_text='Unique ID for the section on the page, e.g., hero_section, mission_section', max_length=100, verbose_name='Section Identifier')),
                ('title', models.CharField(blank=True, help_text='Main heading for the section', max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Secondary heading or lead-in text', max_length=255, null=True, verbose_name='Subtitle')),
                ('body_text', models.TextField(blank=True, help_text='Main paragraph content for the section', null=True, verbose_name='Body Text')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the section', null=True, upload_to='page_backgrounds/', verbose_name='Background Image')),
                ('background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the background image', max_length=255, null=True, verbose_name='Background Image Alt Text')),
                ('order', models.IntegerField(default=0, help_text='Display order of this content block within its section', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page_name', 'section_identifier', 'order'],
                'abstract': False,
                'unique_together': {('page_name', 'section_identifier')},
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('button_text', models.CharField(max_length=100, verbose_name='Button Text')),
                ('button_url', models.URLField(help_text='URL the button links to', verbose_name='Button URL')),
                ('order', models.IntegerField(default=0, help_text='Display order of the button', verbose_name='Order')),
                ('page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to_actions', to='cms_content.pagecontent', verbose_name='Page Content Block')),
            ],
            options={
                'verbose_name': 'Call To Action Button',
                'verbose_name_plural': 'Call To Action Buttons',
                'ordering': ['page_content', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('image', models.ImageField(upload_to='product_carousel/', verbose_name='Image')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt Text')),
                ('order', models.IntegerField(default=0, help_text='Display order in the product carousel', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms_content.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['product', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(help_text='Heading for the section, e.g., Key Features, Applications', max_length=255, verbose_name='Section Title')),
                ('order', models.IntegerField(default=0, help_text='Display order of sections on the product detail page', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms_content.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Section',
                'verbose_name_plural': 'Product Sections',
                'ordering': ['product', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('text', models.TextField(help_text='Content of the list item. HTML formatting may be used.', verbose_name='Item Text')),
                ('order', models.IntegerField(default=0, help_text='Display order of items within the section', verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms_content.productsection', verbose_name='Product Section')),
            ],
            options={
                'verbose_name': 'Product Section Item',
                'verbose_name_plural': 'Product Section Items',
                'ordering': ['section', 'order'],
                'abstract': False,
            },
        ),
    ]
