# Generated by Django 5.2.3 on 2025-06-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('image', models.ImageField(upload_to='case_studies/', verbose_name='Image')),
                ('image_alt_text', models.CharField(max_length=255, verbose_name='Image Alt Text')),
                ('url_slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhitePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('file', models.FileField(upload_to='white_papers/', verbose_name='File')),
                ('url_slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'White Paper',
                'verbose_name_plural': 'White Papers',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
