# Generated by Django 5.2.3 on 2025-06-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0002_casestudy_whitepaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Image')),
                ('image_alt_text', models.CharField(max_length=255, verbose_name='Image Alt Text')),
                ('content', models.TextField(verbose_name='Content')),
                ('url_slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['publish_date', 'order'],
                'abstract': False,
            },
        ),
    ]
